services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${PORT}:8000
            - 8081:8081
        environment:
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            - WORKERS=${WORKERS}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${CONFIG_FILE}:/app/src/pwncore/config.py
            - ./src:/app/src
        depends_on:
            - db

    db:
        image: postgres:14
        user: ${UID}:${GID}
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/var/lib/postgresql/data/pgdata
        healthcheck: 
            interval: 10s
            retries: 10
            test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
            timeout: 2s
        volumes:
            - ${DATA_PATH}:/var/lib/postgresql/data
        ports:
            - 5432:5432


    admin_db:
        image: nocodb/nocodb:latest
        volumes:
            - ./data:/usr/app/data
        ports:
            - 8001:8080